export const FETCH_NEWS = "FETCH_NEWS";

export const FETCH_DOCUMENTATIONS = "FETCH_DOCUMENTATIONS";
export const EXPAND_COLLAPSE_DOC = "EXPAND_COLLAPSE_DOC";
export const EXPAND_COLLAPSE_SERVICE = "EXPAND_COLLAPSE_SERVICE";

export const FETCH_DAX_FUNCTIONS = "FETCH_DAX_FUNCTIONS";
export const FETCH_DAX_FUNCTIONS_CATEGORIES = "FETCH_DAX_FUNCTIONS_CATEGORIES";
export const EXPAND_COLLAPSE_DAX_FUNCTION = "EXPAND_COLLAPSE_DAX_FUNCTION";

export const FETCH_COMMUNITY_DOCUMENTS = "FETCH_COMMUNITY_DOCUMENTS"
export const FETCH_COMMUNITY_LINKS = "FETCH_COMMUNITY_LINKS"

export const FETCH_INFLUENCERS= "FETCH_INFLUENCERS"

export const FETCH_COURSES= "FETCH_COURSES"
export const FETCH_COURSE= "FETCH_COURSE"

export const FETCH_LEARNING_PATHS = "FETCH_LEARNING_PATHS"

export const FETCH_EXAMS = "FETCH_EXAMS"
export const FETCH_EXAM = "FETCH_EXAM"
export const CHANGE_ANSWER = "CHANGE_ANSWER"

export const USER_LOGIN = "USER_LOGIN"