export const FETCH_NEWS = "FETCH_NEWS";

export const FETCH_DOCUMENTATIONS = "FETCH_DOCUMENTATIONS";
export const EXPAND_COLLAPSE_DOC = "EXPAND_COLLAPSE_DOC";
export const EXPAND_COLLAPSE_SERVICE = "EXPAND_COLLAPSE_SERVICE";